name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build_and_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install & Build Angular
        run: |
          npm install
          npm run build --prod

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          # ← Your SWA deployment token (set this secret in GitHub)
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}

          # ← For automatic PR comments; leave as-is
          repo_token: ${{ secrets.GITHUB_TOKEN }}

          # ← We want “upload” since we already built above
          action: upload

          # Your source code folder (root for Angular CLI projects)
          app_location: "/"

          # ← This must point to where index.html actually lives
          app_artifact_location: "dist/angular-basic"

          # We pre-built above, so skip the built-in build step
          skip_app_build: true
          skip_api_build: true
